### ISSUE TITLE
Cannot obtain a profile (e.g. via `gmon.out`)

### ISSUE THREAD

**Issue by paulreimer** [espressif/openocd-esp32#36] opened 2018-04-12 01:37 UTC
I am not sure how to obtain a valid profile (e.g. something in `gmon.out` format such as can be inspected via `xtensa-esp32-elf-gprof`).

From reading the list of commands, it seems I should be able to run:
```
> profile 5 gmon.out
```

However, I get this output from `openocd`, printing endlessly for the 5 seconds requested:
```
> profile 5 gmon.out
Starting profiling. Halting and resuming the target as often as we can...
Target halted. PRO_CPU: PC=0x40100F6D (active)    APP_CPU: PC=0x00000000
esp32: target state: halted
Target halted. PRO_CPU: PC=0x40100F6D (active)    APP_CPU: PC=0x00000000
esp32: target state: halted
Target halted. PRO_CPU: PC=0x40100F6D (active)    APP_CPU: PC=0x00000000
esp32: target state: halted
...
```
and eventually finally:
```
Info : Profiling completed. 35 samples.
Assertion failed: (addressSpace >= 2), function write_gmon, file target.c, line 3873.
```

And this repeating error on the target:
```
Guru Meditation Error: Core  0 panic'ed (StoreProhibited)
 at pc=40100f6d. Setting bp and returning..
Guru Meditation Error: Core  0 panic'ed (StoreProhibited)
 at pc=40100f6d. Setting bp and returning..
...
```

**Comment by igrr** [comment] 2018-05-25 13:27
Hi @paulreimer, sorry for the slow response.
It appears that the problem is in the part of OpenOCD code which builds the histogram of samples. It tries to figure out the size of single histogram bucket here:

https://github.com/espressif/openocd-esp32/blob/370c35e6758edd43b28d943960a181a58ecd523c/src/target/target.c#L3851-L3873

The failing assert expresses the assumption that there are at least two different PC values in profiling data. In your case it appears that all PC values are the same (probably pointing to waiti instruction of the idle task). This causes the check to fail.

You can overcome this problem by passing the address range for profiling, e.g.:
```
profile 5 gmon.out 0x40000000 0x40400000
```

The other part of the problem, related to StoreProhibited, should be fixed in latest master (and latest release) — it seems to be caused by register value corruption when OpenOCD halts and then resumes the program.

**Closed** 2018-05-29 14:35 UTC
